version: '3'

services:
  wordpress:
    container_name: base_wp
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./docker/wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/theme
      - ./theme-plugin:/var/www/html/wp-content/plugins/theme-plugin
    ports:
      - "3080:80"
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my_wordpress_db_password

  db:
    container_name: base_db
    image: mariadb
    volumes:
      - ./docker/db:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: mypassword1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_db_password
volumes:
  docker:
  'theme':
  'theme-plugin':
